# Generated by Django 3.1.2 on 2020-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='OTPGeneratedTime',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
